ktor {
  deployment {
    port = 8080
    port = ${?PORT}
    host = "0.0.0.0"
    host = ${?HOST}
    shutdownGracePeriod = 30000
    shutdownTimeout = 30000
  }

  application {
    modules = [ run.trama.app.ApplicationKt.module ]
  }

  environment = "prod"
  environment = ${?APP_ENV}
}

app {
  metrics {
    enabled = true
    enabled = ${?METRICS_ENABLED}
  }
}
